name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          # submodules: true


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: 编译
        run: |
          npm run build
          echo 'graph.jdk.plus' > dist/CNAME

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh_pages
          folder: dist
          token: ${{ secrets.GH_PAGES_TOKEN }}
